name: HTML/CSS Validation

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install validation tools
      run: |
        npm install -g htmlhint stylelint stylelint-config-standard
    
    - name: Validate HTML
      run: |
        htmlhint "/*.html"
      continue-on-error: true
    
    - name: Validate CSS
      run: |
        echo '{"extends": "stylelint-config-standard"}' > .stylelintrc.json
        stylelint "/*.css"
      continue-on-error: true
    
    - name: Run HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
        css: true
        extra: --log INFO --ignore-re "Attribute."
        fail_action: false